Feats #43 Convert the application to blazor server side
STARIONGROUP/reqifviewer pull request #44
Opened 2024-03-19 17:11 UTC by joao4all

…input files

### Prerequisites

- [ ] I have written a descriptive pull-request title
- [ ] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/reqifviewer/pulls) open
- [ ] I have verified that I am following the reqifviewer [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/reqifviewer/master/.github/CONTRIBUTING.md)
- [ ] I have provided test coverage for my change (where applicable)

### Description
Closes #43 Convert the application to blazor server side #43

- Application updated to net8.0
- Migration from webassembly to server side
- Refactor to upload files to server
- Dockerfile updated

2024-03-19 17:48 UTC, joao4all commented
Pipeline is failing. Seems an issue with Java Runtime version

2024-03-20 07:51 UTC, antoineatrhea requested changes
Please also update github workflow files to target net8.0 (.github/workflows)

2024-03-20 08:40 UTC, antoineatrhea approved these changes

2024-03-20 08:55 UTC, samatstariongroup approved these changes

2024-03-20 09:03 UTC, joao4all commented
Additional Info:
- Locally, tests are passing and the project is building/running normally
- Ithis PR will be merged with the failing pipeline => needs to be fixed

2024-03-20 09:06 UTC, merged